# List of stages for jobs, and their order of execution
stages:
    -   build
    -   test
    -   deploy

# This job runs in the build stage, which runs first.
build-job:
    stage: build
    script:
        -   echo "Compiling the code..."
        -   echo "Compile complete."

# This job runs in the test stage.
unit-test-job:
    # It only starts when the job in the build stage completes successfully.
    stage: test
    script:
        -   echo "Running unit tests..."
        -   sleep 30
        -   echo "Tests complete."

# This job also runs in the test stage.
lint-test-job:
    # It can run at the same time as unit-test-job (in parallel).
    stage: test
    script:
        -   echo "Linting code..."
        -   sleep 10
        -   echo "Linting complete."

# This job runs in the deploy stage.
deploy-job:
    # It only runs when *both* jobs in the test stage complete successfully.
    stage: deploy
    environment: production
    script:
        -   echo "Deploying application..."
        -   echo "Application deployed."
