stages:
    -   build-auth
    -   build-users
    -   build-wallets

build-auth:
    stage: build-auth
    image:
        name: gcr.io/kaniko-project/executor:v1.9.0-debug
        entrypoint:
            -   ""
    script:
        -   mkdir -p /kaniko/.docker
        -   echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
        -   /kaniko/executor
                --context "${CI_PROJECT_DIR}/apps/auth"
                --dockerfile "${CI_PROJECT_DIR}/apps/auth/Dockerfile"
                --destination "${CI_REGISTRY}/${CI_PROJECT_PATH}/auth:latest"
build-users:
    stage: build-users
    image:
        name: gcr.io/kaniko-project/executor:v1.9.0-debug
        entrypoint:
            -   ""
    script:
        -   mkdir -p /kaniko/.docker
        -   echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
        -   /kaniko/executor
                --context "${CI_PROJECT_DIR}/apps/users"
                --dockerfile "${CI_PROJECT_DIR}/apps/users/Dockerfile"
                --destination "${CI_REGISTRY}/${CI_PROJECT_PATH}/users:latest"
build-wallets:
    stage: build-wallets
    image:
        name: gcr.io/kaniko-project/executor:v1.9.0-debug
        entrypoint:
            -   ""
    script:
        -   mkdir -p /kaniko/.docker
        -   echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
        -   /kaniko/executor
                --context "${CI_PROJECT_DIR}/apps/wallets"
                --dockerfile "${CI_PROJECT_DIR}/apps/wallets/Dockerfile"
                --destination "${CI_REGISTRY}/${CI_PROJECT_PATH}/wallets:latest"
