stages:
    -   prebuild
    -   build


prebuild:
    stage: prebuild
    image:
        name: gcr.io/kaniko-project/executor:v1.9.0-debug
        entrypoint:
            -   ""
    script:
        -   mkdir -p /kaniko/.docker
        -   echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
build-auth:
    stage: build
    script:
        -   /kaniko/executor
                --context "${CI_PROJECT_DIR}/apps/auth"
                --dockerfile "${CI_PROJECT_DIR}/apps/auth/Dockerfile"
                --destination "${CI_REGISTRY}/${CI_PROJECT_PATH}/auth:latest"
build-users:
    stage: build
    script:
        -   /kaniko/executor
                --context "${CI_PROJECT_DIR}/apps/users"
                --dockerfile "${CI_PROJECT_DIR}/apps/users/Dockerfile"
                --destination "${CI_REGISTRY}/${CI_PROJECT_PATH}/users:latest"

