stages:
    # -   build-auth
    # -   build-users
    # -   build-wallets
    -   deploy

# build-auth:
#     stage: build-auth
#     image:
#         # debug image is recommended because it has shell
#         name: gcr.io/kaniko-project/executor:v1.9.0-debug
#         # entrypoint needs to be overridden
#         entrypoint:
#             -   ""
#     script:
#         # write kaniko config with needed credentials taken from predefined CI/CD variables 
#         -   mkdir -p /kaniko/.docker
#         -   echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
#         # build image and push to project container registry 
#         -   /kaniko/executor
#                 --context "${CI_PROJECT_DIR}/apps/auth"
#                 --dockerfile "${CI_PROJECT_DIR}/apps/auth/Dockerfile"
#                 --destination "${CI_REGISTRY}/${CI_PROJECT_PATH}/auth:latest"
# build-users:
#     stage: build-users
#     image:
#         name: gcr.io/kaniko-project/executor:v1.9.0-debug
#         entrypoint:
#             -   ""
#     script:
#         -   mkdir -p /kaniko/.docker
#         -   echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
#         -   /kaniko/executor
#                 --context "${CI_PROJECT_DIR}/apps/users"
#                 --dockerfile "${CI_PROJECT_DIR}/apps/users/Dockerfile"
#                 --destination "${CI_REGISTRY}/${CI_PROJECT_PATH}/users:latest"
# build-wallets:
#     stage: build-wallets
#     image:
#         name: gcr.io/kaniko-project/executor:v1.9.0-debug
#         entrypoint:
#             -   ""
#     script:
#         -   mkdir -p /kaniko/.docker
#         -   echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
#         -   /kaniko/executor
#                 --context "${CI_PROJECT_DIR}/apps/wallets"
#                 --dockerfile "${CI_PROJECT_DIR}/apps/wallets/Dockerfile"
#                 --destination "${CI_REGISTRY}/${CI_PROJECT_PATH}/wallets:latest"
deploy:
    stage: deploy
    image:
        name: bitnami/kubectl:latest
        entrypoint:
            -   ""
    script:
        -   kubectl config get-contexts
        -   kubectl config use-context alex-gudkov/kubernetes-microservices:primary-agent
        -   kubectl get pods
        # apply
        -   kubectl apply --filename "${CI_PROJECT_DIR}/kubernetes/postgres"
        -   kubectl apply --filename "${CI_PROJECT_DIR}/kubernetes/redis"
        -   kubectl apply --filename "${CI_PROJECT_DIR}/kubernetes/rabbitmq"
        # apply 
        -   kubectl apply --filename "${CI_PROJECT_DIR}/kubernetes/auth"
        -   kubectl apply --filename "${CI_PROJECT_DIR}/kubernetes/users"
        -   kubectl apply --filename "${CI_PROJECT_DIR}/kubernetes/wallets"
        # 
        -   kubectl get pods
