version: '3.7'

services:
    redis:
        container_name: kubernetes_microservices_redis
        image: redis:7
        ports:
            - 6379:6379
        environment:
            REDIS_HOST: localhost
            REDIS_PORT: 6379
        volumes:
            - ./redis_data:/data
    postgres:
        container_name: kubernetes_microservices_postgres
        image: postgres:14
        ports:
            - 5432:5432
        environment:
            POSTGRES_HOST: localhost
            POSTGRES_PORT: 5432
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root
            POSTGRES_DB: kubernetes_microservices
        volumes:
            - ./pg_data:/var/lib/postgresql
    rabbitmq:
        container_name: kubernetes_microservices_rabbitmq
        image: rabbitmq:3
        ports:
            - 15672:15672
            - 5672:5672
volumes:
    pg_data:
    redis_data:
