version: '3.8'

services:
  redis:
    container_name: kubernetes_microservices_dev_redis
    image: redis:7.0.10
    ports:
      - 6379:6379
    volumes:
      - ./redis_data:/data
  postgres:
    container_name: kubernetes_microservices_dev_postgres
    image: postgres:15.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      POSTGRES_DB: "kubernetes_microservices"
    volumes:
      - ./pg_data:/var/lib/postgresql
  rabbitmq:
    container_name: kubernetes_microservices_dev_rabbitmq
    image: rabbitmq:3.11.11
    ports:
      - 5672:5672
volumes:
  pg_data:
  redis_data:
