apiVersion: apps/v1
kind: Deployment
metadata:
    name: rabbitmq
    labels:
        app.kubernetes.io/name: kubernetes-microservices
        app.kubernetes.io/component: rabbitmq
spec:
    replicas: 1
    selector:
        matchLabels:
            app.kubernetes.io/name: kubernetes-microservices
            app.kubernetes.io/component: rabbitmq
    template:
        metadata:
            labels:
                app.kubernetes.io/name: kubernetes-microservices
                app.kubernetes.io/component: rabbitmq
        spec:
            containers:
                -   name: rabbitmq
                    image: rabbitmq:3.11.11
                    imagePullPolicy: IfNotPresent
                    ports:
                        -   name: port-rabbitmq
                            containerPort: 5672
                    resources:
                        limits:
                            memory: 2Gi
                            ephemeral-storage: 1Gi
                            cpu: 500m
                        requests:
                            memory: 2Gi
                            ephemeral-storage: 1Gi
                            cpu: 500m
            restartPolicy: Always
