apiVersion: v1
kind: Service
metadata:
    name: auth
spec:
    selector: 
        app: auth
    ports:
        -   name: port-3001
            protocol: TCP
            port: 3001
            targetPort: 3001
    type: NodePort
