apiVersion: apps/v1
kind: Deployment
metadata:
    name: auth
spec:
    selector:
        matchLabels:
            app: auth
    replicas: 1
    template:
        metadata:
            labels:
                app: auth
        spec:
            containers:
                -   name: auth
                    image: alexgudkov/kubernetes-microservices-auth
                    ports:
                        -   containerPort: 3001
                    env:
                        -   name: APP_PORT
                            value: "3001"
                        -   name: RABBITMQ_USERS_URL
                            value: "amqp://rabbitmq:5672"
                        -   name: RABBITMQ_USERS_QUEUE
                            value: "USERS"
                        -   name: RABBITMQ_AUTH_URL
                            value: "amqp://rabbitmq:5672"
                        -   name: RABBITMQ_AUTH_QUEUE
                            value: "AUTH"
                        -   name: REDIS_URL
                            value: "redis://redis:6379"
                    resources:
                        limits:
                            memory: 256Mi
                            cpu: 500m
                        requests:
                            memory: 128Mi
                            cpu: 100m
