apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: ingress-nginx
    labels:
        app.kubernetes.io/name: kubernetes-microservices
        app.kubernetes.io/component: ingress-nginx
spec:
    rules:
        -   http:
                paths:
                    -   path: /m1
                        pathType: Prefix
                        backend:
                            service:
                                name: auth
                                port:
                                    name: port-auth
                    -   path: /m2
                        pathType: Prefix
                        backend:
                            service:
                                name: users
                                port:
                                    name: port-users
                    -   path: /m3
                        pathType: Prefix
                        backend:
                            service:
                                name: wallets
                                port:
                                    name: port-wallets  
