apiVersion: apps/v1
kind: Deployment
metadata:
    name: postgres
    selector:
        matchLabels:
            app.kubernetes.io/name: kubernetes-microservices
            app.kubernetes.io/component: postgres
spec:
    replicas: 1
    selector:
        matchLabels:
            app.kubernetes.io/name: kubernetes-microservices
            app.kubernetes.io/component: postgres
    template:
        metadata:
            labels:
                app.kubernetes.io/name: kubernetes-microservices
                app.kubernetes.io/component: postgres
        spec:
            containers:
                -   name: postgres
                    image: postgres:15.2
                    imagePullPolicy: IfNotPresent
                    ports:
                        -   name: postgres-port-5432
                            containerPort: 5432
                    env:
                        -   name: POSTGRES_DB
                            value: "kubernetes_microservices"
                        -   name: POSTGRES_PASSWORD
                            value: "root"
                        -   name: POSTGRES_USER
                            value: "postgres"
                    volumeMounts:
                        -   name: postgres-pv-storage
                            mountPath: /var/lib/postgresql/data
            restartPolicy: Always
            volumes:
                -   name: postgres-pv-storage
                    persistentVolumeClaim:
                        claimName: postgres-pv-claim
