apiVersion: apps/v1
kind: Deployment
metadata:
    name: redis
    labels:
        app.kubernetes.io/name: kubernetes-microservices
        app.kubernetes.io/component: redis
spec:
    replicas: 1
    selector:
        matchLabels:
            app.kubernetes.io/name: kubernetes-microservices
            app.kubernetes.io/component: redis
    template:
        metadata:
            labels:
                app.kubernetes.io/name: kubernetes-microservices
                app.kubernetes.io/component: redis
        spec:
            containers:
                -   name: redis
                    image: redis:7.0.10
                    imagePullPolicy: IfNotPresent
                    ports:
                        -   name: port-6379
                            containerPort: 6379
            restartPolicy: Always
