apiVersion: apps/v1
kind: Deployment
metadata:
    name: users
    labels:
        app.kubernetes.io/name: kubernetes-microservices
        app.kubernetes.io/component: users
spec:
    replicas: 1
    selector:
        matchLabels:
            app.kubernetes.io/name: kubernetes-microservices
            app.kubernetes.io/component: users
    template:
        metadata:
            labels:
                app.kubernetes.io/name: kubernetes-microservices
                app.kubernetes.io/component: users
        spec:
            containers:
                -   name: users
                    image: alexgudkov/kubernetes-microservices-users
                    imagePullPolicy: IfNotPresent
                    ports:
                        -   name: port-users
                            containerPort: 3002
                    env:
                        # application
                        -   name: APP_PORT
                            value: "3002"
                        # RabbitMQ
                        -   name: RABBITMQ_URL
                            value: "amqp://rabbitmq:5672"
                        # PostgeSQL
                        -   name: POSTGRES_HOST
                            value: "postgres"
                        -   name: POSTGRES_PORT
                            value: "5432"
                        -   name: POSTGRES_USER
                            value: "postgres"
                        -   name: POSTGRES_PASSWORD
                            value: "root"
                        -   name: POSTGRES_DB
                            value: "kubernetes_microservices"
                    resources:
                        limits:
                            memory: 512Mi
                            cpu: 250m
                        requests:
                            memory: 512Mi
                            cpu: 250m
            restartPolicy: Always
