name: Development
run-name: development
on:
  push:
    branches:
      - main
      - dev
jobs:
  auth-microservice:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/auth
    strategy:
      matrix:
        node-version:
          - 18.x
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: ./apps/auth/package-lock.json
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Prettier
        run: npm run prettier:check
      - name: ESLint
        run: npm run eslint
      - name: Test
        run: npm run test
      - name: Build project
        run: npm run build
  users-microservice:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/users
    strategy:
      matrix:
        node-version:
          - 18.x
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: ./apps/users/package-lock.json
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Prettier
        run: npm run prettier:check
      - name: ESLint
        run: npm run eslint
      - name: Test
        run: npm run test
      - name: Build project
        run: npm run build
  wallets-microservice:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/wallets
    strategy:
      matrix:
        node-version:
          - 18.x
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: ./apps/wallets/package-lock.json
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Prettier
        run: npm run prettier:check
      - name: ESLint
        run: npm run eslint
      - name: Test
        run: npm run test
      - name: Build project
        run: npm run build
