apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app.kubernetes.io/name: kubernetes-microservices
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kubernetes-microservices
    app.kubernetes.io/component: postgres
  ports:
    - name: port-postgres
      protocol: TCP
      port: 5432
      targetPort: port-postgres
